# Generated by Django 4.2.3 on 2023-07-05 08:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('father_name', models.CharField(blank=True, max_length=150, null=True)),
                ('citizenship_id', models.CharField(blank=True, max_length=50, null=True)),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], default='A+', max_length=150)),
                ('address', models.CharField(blank=True, max_length=150, null=True)),
                ('phone_no', models.CharField(blank=True, max_length=10, null=True)),
                ('category', models.CharField(choices=[('A', 'A - Motorcycle, Scooter, Moped'), ('B', 'B - Car, Jeep, Delivery Van'), ('C', 'C - Tempo, Auto Rickshaw'), ('C1', 'C1 - E-Rickshaw'), ('D', 'D - Power Tiller'), ('E', 'E - Tractor'), ('F', 'F - Minibus, Minitruck'), ('G', 'G - Truck, Bus, Lorry'), ('H', 'H - Road Roller, Dozer'), ('K', 'K - Scooter, Moped')], default='A', max_length=10)),
                ('photo', models.ImageField(blank=True, default='user_photo/avatar.svg', null=True, upload_to='user_photo')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('examiner', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='goodaau.userdetail')),
            ],
        ),
    ]
