# Generated by Django 4.2.3 on 2023-07-07 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodaau', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='marks',
            field=models.IntegerField(default=0),
        ),
    ]
