# Generated by Django 4.2.3 on 2023-07-08 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goodaau', '0002_exam_marks'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pass_file', models.FileField(upload_to='pass_report')),
                ('appointment_date', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='goodaau.userdetail')),
            ],
        ),
    ]
